version: 2
updates:
- package-ecosystem: "docker"
  directory: "/manylinux2014_x86_64"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/manylinux2014_i686"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/manylinux2014_aarch64"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/manylinux2014_ppc64le"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/manylinux2014_s390x"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/musllinux_1_2_x86_64"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/musllinux_1_2_aarch64"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"