name: Auto approve Dependabot

on: pull_request


jobs:
  auto-approve:
    if: contains(github.event.pull_request.labels, 'docker') && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4

  debug-label:
    runs-on: ubuntu-latest
    steps:
      - run: echo "labels are ${{ github.event.pull_request.labels }}"

  debug-actor:
    runs-on: ubuntu-latest
    steps:
      - run: echo "actor is ${{ github.actor }}"
