name: Auto approve Dependabot

on: pull_request


jobs:
  auto-approve:
    if: contains(github.event.pull_request.labels, 'docker') && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4