name: Build and publish manylinux2014_aarch64

on: 
  workflow_dispatch:
  push:
    branches: 
    - "main"
    paths:
    - "manylinux2014_aarch64/Dockerfile"

jobs:
  build-and-publish:
    uses: "./.github/workflows/publish_docker.yml"
    with:
      imagename: "manylinux2014_aarch64"
      platform: "linux/amd64"