name: Build and publish manylinux2014_x86_64

on: 
  workflow_dispatch:
  push:
    branches: 
    - "main"
    paths:
    - "x86_64/Dockerfile"

jobs:
  build-and-publish:
    uses: "./.github/workflows/publish_docker.yml"
    with:
      imagename: "manylinux2014_x86_64"
      platform: "linux/amd64"