name: Build and publish manylinux2014_ppc64le

concurrency: manylinux2014_ppc64le

on: 
  workflow_dispatch:
  push:
    branches: 
    - "main"
    paths:
    - "manylinux2014_ppc64le/Dockerfile"

jobs:
  build-and-publish:
    uses: "./.github/workflows/publish_docker.yml"
    with:
      imagename: "manylinux2014_ppc64le"
      platform: "linux/ppc64le"
    permissions: 
      packages: write
