name: Build and publish manylinux2014_i686

concurrency: manylinux2014_i686

on: 
  workflow_dispatch:
  push:
    branches: 
    - "main"
    paths:
    - "manylinux2014_i686/Dockerfile"

jobs:
  build-and-publish:
    uses: "./.github/workflows/publish_docker.yml"
    with:
      imagename: "manylinux2014_i686"
      platform: "linux/386"
    permissions: 
      packages: write
