name: Build and publish musllinux_1_2_aarch64

on: 
  workflow_dispatch:
  push:
    branches: 
    - "main"
    paths:
    - "musllinux_1_2_aarch64/Dockerfile"

jobs:
  build-and-publish:
    uses: "./.github/workflows/publish_docker.yml"
    with:
      imagename: "musllinux_1_2_aarch64"
      platform: "linux/arm64/v8"