name: Build and publish Docker images

on: 
  workflow_call:   
    inputs:
      dockerfile:
        description: 'Relative path to Dockerfile'
        type: string
        required: true
      imagename:
        description: 'Base name to use for uploaded image: E.g.: "manylinux2014_x86_64"'
        type: string
        required: true
      platform:
        description: 'Platform to build for. E.g.: "linux/amd64" or "linux/arm64/v8"'
        type: string
        required: true

jobs:
  build-and-publish:
    name: build ${{ inputs.dockerfile }}
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.dockerfile }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: ${{ inputs.platform }}
        tags: ghcr.io/musicalninjas/${{ inputs.imagename }}-rust