name: Build and publish Docker images

on: 
  workflow_call:   
    inputs:
      imagename:
        description: 'Base name to use for uploaded image: E.g.: "manylinux2014_x86_64"'
        type: string
        required: true
      platform:
        description: 'Platform to build for. E.g.: "linux/amd64" or "linux/arm64/v8"'
        type: string
        required: true

jobs:
  build-and-publish:
    name: build ${{ inputs.imagename }}
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: get tag
      id: tag
      run: |
        echo "TAG=$(grep FROM ${{ inputs.imagename }}/Dockerfile | awk --field-separator=':' '{ print $2 }')" >> "$GITHUB_OUTPUT"

    - name: set docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/musicalninjas/${{ inputs.imagename }}-rust
          ghcr.io/musicalninjas/quay.io/pypa/${{ inputs.imagename }}-rust
        flavor: |
          latest=true
        tags: |
          type=raw,${{ steps.tag.outputs.TAG }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.imagename }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: ${{ inputs.platform }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}